/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.videoclub;

import java.awt.BorderLayout;

/**
 *
 * @author njorg
 */
public class panelMenuArriendos extends javax.swing.JPanel {
    private CollectionManager collectionManager;
    /**
     * Creates new form panelMenuArriendos
     */
    public panelMenuArriendos(CollectionManager mc) {
        initComponents();
        collectionManager = mc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonCrearArriendo = new javax.swing.JButton();
        botonDevolverArriendo = new javax.swing.JButton();
        botonMostrarArriendos = new javax.swing.JButton();
        panelContent = new javax.swing.JPanel();

        botonCrearArriendo.setText("Crear Arriendo");
        botonCrearArriendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearArriendoActionPerformed(evt);
            }
        });

        botonDevolverArriendo.setText("Devolver Arriendo");
        botonDevolverArriendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDevolverArriendoActionPerformed(evt);
            }
        });

        botonMostrarArriendos.setText("Mostrar Arriendos");
        botonMostrarArriendos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarArriendosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelContentLayout = new javax.swing.GroupLayout(panelContent);
        panelContent.setLayout(panelContentLayout);
        panelContentLayout.setHorizontalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 623, Short.MAX_VALUE)
        );
        panelContentLayout.setVerticalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonDevolverArriendo, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(botonCrearArriendo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonMostrarArriendos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(botonCrearArriendo)
                .addGap(18, 18, 18)
                .addComponent(botonDevolverArriendo)
                .addGap(18, 18, 18)
                .addComponent(botonMostrarArriendos)
                .addContainerGap(340, Short.MAX_VALUE))
            .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearArriendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearArriendoActionPerformed
        panelCrearArriendo panelArriendo = new panelCrearArriendo(collectionManager);
        panelArriendo.setSize(623,514);
        panelArriendo.setLocation(0,0);
        panelContent.removeAll();
        panelContent.add(panelArriendo,BorderLayout.CENTER);
        panelContent.revalidate();
        panelContent.repaint();
    }//GEN-LAST:event_botonCrearArriendoActionPerformed

    private void botonDevolverArriendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDevolverArriendoActionPerformed
        panelDevolver panelDevol = new panelDevolver(collectionManager);
        panelDevol.setSize(623,514);
        panelDevol.setLocation(0,0);
        panelContent.removeAll();
        panelContent.add(panelDevol,BorderLayout.CENTER);
        panelContent.revalidate();
        panelContent.repaint();
    }//GEN-LAST:event_botonDevolverArriendoActionPerformed

    private void botonMostrarArriendosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarArriendosActionPerformed
        panelMostrarArriendos panelMostrar = new panelMostrarArriendos(collectionManager);
        panelMostrar.setSize(623,514);
        panelMostrar.setLocation(0,0);
        panelContent.removeAll();
        panelContent.add(panelMostrar,BorderLayout.CENTER);
        panelContent.revalidate();
        panelContent.repaint();
    }//GEN-LAST:event_botonMostrarArriendosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrearArriendo;
    private javax.swing.JButton botonDevolverArriendo;
    private javax.swing.JButton botonMostrarArriendos;
    private javax.swing.JPanel panelContent;
    // End of variables declaration//GEN-END:variables
}
